### ISSUE TITLE
Admin tasks E2.75

### ISSUE THREAD

**Issue by Joepock123** [tech-for-better/spokesafe-frontend#1]
- [x] Set up repo and file structure (including routes with React Router), import React **P1 - E0.5**
- [x] Create React app **P1 - E0**
- [x] Deploy using Firebase **P2 - E0.5**
- [ ] Maintain readme and handover docs **P1 - E0.75**
- [x] Set up StoryBook, Styled Components  **P2 - E0**
- [x] ESLint, Prettier **P1 - E0.25**
- [ ] Travis or Circle, CodeCov **P2 - E0.25**
- [ ] Testing Spike: Jest (and whatever needed for Firebase testing) **P2 - E0.5**
- [ ] Other bits and pieces - style guide **P3 - E0**
- [x] Set up type checking for tests in typescript create-react-app **P2-E0**

**Comment by VatsKan** [comment]
closing issue as will be logging issues differently from now on. incomplete issues have been copied over to an excel doc
