### ISSUE TITLE
Shared Components E1

### ISSUE THREAD

**Issue by Joepock123** [tech-for-better/spokesafe-frontend#2]
## Images/Icons E**0**

- [x] Logo

## Buttons E**0.25**

- [ ] Menu burger
- [x] Primary button (Black & Yellow versions)
- [x] 'choose' button
- [x] Back arrow
- [x] More information button

##  Styles E**0.25**

- [x] Shared Stylings — (fonts which Kalle gave us)

## Text E**0.25**

- [x] Page Headers (small one at top + 'Welcome')
- [x] Stage in process component
- [ ] History of previous selections (on forms)
- [x] Paragraph text

## Form E**0.75**

- [x] inputs
- [x] labels

## Logic **E0.25**

ProtectedRoute. X

**Comment by VatsKan** [comment]
closing issue as will be logging issues differently from now on. incomplete issues have been copied over to an excel doc
