### ISSUE TITLE
Database setup E1.5

### ISSUE THREAD

**Issue by Joepock123** [tech-for-better/spokesafe-frontend#3]
- [x] Decide on db structure 
- Collections: 
 - [x] 1) subscription plan table [plan, price]. 
 - [x] 2) users [first name, last name, email, password, mudguard, ebike] 
 - [ ] 3) locations [location, address, number of available space, more-detailed-instructions (e.g. on 2nd floor of car park)]
- [x] Build initial db
- [ ] Further research on Firestore

**Comment by VatsKan** [comment]
closing issue as will be logging issues differently from now on. incomplete issues have been copied over to an excel doc
